# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-02 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_inves'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inves',
            old_name='direccion',
            new_name='institucion',
        ),
    ]
