# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20161103_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inves',
            name='celular',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inves',
            name='ext',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='inves',
            name='sni',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
