# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-10 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20161110_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=140)),
                ('institucion_empresa', models.CharField(max_length=140)),
                ('cargo', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('telefono', models.IntegerField()),
                ('ext', models.IntegerField(blank=True, null=True)),
                ('celular', models.IntegerField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('producto', models.CharField(blank=True, max_length=140, null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
